### ISSUE TITLE
How I can use it on my website?

### ISSUE THREAD

**Issue by GoldenScrew** [sonatra/sonatra-jquery-sidebar#2]
Hello, I do mobile version of website. How I can use it on my website?
Is this only for apps? Or no? Sorry for my dumb question. Hope understanding, thanks.

**Comment by GoldenScrew** [comment]
I can't find sidebar.css.

**Comment by francoispluchino** [comment]
Of course, technically you can use this component to a website, and not only for an application. After, it is an ergonomic choice.

You can find examples of uses: https://github.com/sonatra/sonatra-jquery-sidebar/tree/master/examples.

**Comment by francoispluchino** [comment]
It's normally, you must use `less` compiler for build the css.

See the installation doc: https://github.com/sonatra/sonatra-jquery-sidebar/blob/master/doc/index.md.

**Comment by bryanwillis** [comment]
Here's an example I just compiled on codepen: 
http://codepen.io/bootstrapped/details/pbkPYZ/

Or for same thing with css copiled:
https://gist.github.com/bryanwillis/5369b70224c0571b58d72e38e63c474a 

It seems like there's a few quirks in the latest release though when switching from dragging to clicking the icon. 

Also here's an older version I noticed online:
http://www.jqueryscript.net/demo/Responsive-Fluid-Sidebar-Plugin-with-jQuery-Hammer-js/

**Comment by bryanwillis** [comment]
Not sure if you intended on this to be a big thing or not @francoispluchino but it would probably get way more action if you included a distribution version for people who don't know how to compile less.

**Comment by francoispluchino** [comment]
Yes, probably, but I'm still not taken care of this issue. For the moment, I focused on the overall project, and I still do the documentation, demos and distributed versions.
