### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by rodrigogalindez** [sonatra/sonatra-jquery-sidebar#4]
Hi there, 

I downloaded the ZIP, and the example HTMLs inside the /examples directory won't work. There are .css files missing. Also, only .less versions of the .css files found. Can you give more info? Thanks.

**Comment by francoispluchino** [comment]
Install dependencies with NPM (or Yarn):

```
$ npm install
```
And run grunt with the command:
```
$ grunt
```
or
```
$ grunt serve
```

If you want only build the css, run:
```
$ grunt less
```
