### ISSUE TITLE
Sidebar initialize without using data attribute.

### ISSUE THREAD

**Issue by igsavenko** [sonatra/sonatra-jquery-sidebar#5]
How can I initialize the sidebar through the Sidebar class manually or as jQuery plugin $('#selector').sidebar()? Without using data-sidebar=true? I want to override default params object - Sidebar.DEFAULTS = {} and add my own clasess. Thanks.

**Comment by francoispluchino** [comment]
To use sidebar in code:
```js
$('#my-sidebar').sidebar({
  'locked': true
});
```

To override the default options:
```js
$.fn.sidebar.Constructor.DEFAULTS = $.extend(true, {}, $.fn.sidebar.Constructor.DEFAULTS, {
  locked: true // old default value: false
});
```

**Comment by igsavenko** [comment]
Hm. Very interesting. But i got `$(...).sidebar is not a function.` One clarification, I use npm and webpack.
I tried several ways (import, require), but result always similar.
```javascript
import 'hammerjs/hammer.js';
import "@sonatra/jquery-sidebar/js/sidebar.js";

$('.j_sidebar_mobile').sidebar({'locked': true});`

**Comment by francoispluchino** [comment]
Ok, you uses Webpack. This library is a plugin for jquery and works with the html imports. But, have you see the doc to use Jquery with Webpack or this [stackoverflow post](https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack)?

When I use Jquery and plugins, I configure Webpack with the `noParse` option, but I would be happy to make my plugins compatible (without `noParse`), if you know how to do it.
