### ISSUE TITLE
Can't install npm package

### ISSUE THREAD

**Issue by beardlessman** [sonatra/sonatra-jquery-sidebar#6]
Hi! I have a problem with installation the plugin from npmjs.org.

Command from docs:
npm install @fxp/jquery-sidebar --save

Result:
npm ERR! code E404
npm ERR! 404 Not Found: @fxp/jquery-sidebar@latest

Can you help me?

**Comment by francoispluchino** [comment]
This package hasn't release because it is in development. With NPM, it's preferable to not registering the package in NPM Registry without first stable version, which was not the case of Bower. I must update the doc. So, you must use the git link.

Run this command:

```
$ npm install fxpio/fxp-jquery-sidebar#master --save
```

**Comment by beardlessman** [comment]
thanks! :+1:
